name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # 添加写入权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # 更新到 v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3  # 更新到 v3
        with:
          java-version: '8'
          distribution: 'temurin'  # 指定发行版

      - name: Build with Maven
        run: mvn clean package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      # 为不同操作系统打包
      - name: Package for Windows
        run: |
          mkdir -p release/windows
          cp target/*.jar release/windows/
          echo "@echo off" > release/windows/start.bat
          echo "java -jar *.jar" >> release/windows/start.bat
          cd release && zip -r windows.zip windows/

      - name: Package for Linux
        run: |
          mkdir -p release/linux
          cp target/*.jar release/linux/
          echo "#!/bin/bash" > release/linux/start.sh
          echo "java -jar *.jar" >> release/linux/start.sh
          chmod +x release/linux/start.sh
          cd release && tar -czf linux.tar.gz linux/

      - name: Package for macOS
        run: |
          mkdir -p release/macos
          cp target/*.jar release/macos/
          echo "#!/bin/bash" > release/macos/start.sh
          echo "java -jar *.jar" >> release/macos/start.sh
          chmod +x release/macos/start.sh
          cd release && zip -r macos.zip macos/
      
      # 上传发布包
      - name: Upload Windows Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/windows.zip
          asset_name: windows.zip
          asset_content_type: application/zip

      - name: Upload Linux Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/linux.tar.gz
          asset_name: linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/macos.zip
          asset_name: macos.zip
          asset_content_type: application/zip 